version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data

  worker:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.worker
    container_name: worker
    ports:
     - "9090:9090"
    environment:
      HTTP_ADDR: ":9090"
      PG_URL: "postgres://postgres:postgres@postgres/callback?sslmode=disable"

  master:
    depends_on:
      - postgres
      - worker
    build:
      context: ./
      dockerfile: Dockerfile.master
    container_name: master
    ports:
      - "9010:9010"
    environment:
      HTTP_ADDR: ":9010"