version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authtest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - authservice  

  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5456:5456"
    depends_on:
      - db  
    networks:
      - authservice  

volumes:
  pgdata:

networks:
  authservice:
    name: authservice
    driver: bridge  